spring.application.name=alexandria
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=8080

# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/alexandria
spring.datasource.username=postgres
spring.datasource.password=Eder12345678!@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
# Recomendo colocar uma chave secreta aqui para evitar erros ao subir a aplicação
jwt.secret=essaEhUmaChaveMuitoLongaEQualquerParaTeste123456
jwt.expiration=86400000